

services:

# Irregularity of data formats resulting from the conversion of database files
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.backend
#    ports:
#      - "8002:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"

