

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8002:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

